name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pnpm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script: [lint, test, build]
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Install Dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Run Script ${{ matrix.script }}
        run: pnpm ${{ matrix.script }}
